# This workflow will do a clean install of node dependencies and build the source code across different node versions

name: Node.js CI and Grunt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 2.7.x
    - run: npm install -g grunt-cli
    - run: npm ci
    - run: grunt build
      env:
        CI: true
